# Generated by Django 3.2.12 on 2022-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
